production:
  adapter: postgresql
  encoding: unicode
  database: your_production_db
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: 5

cable:
  <<: *default
  database: your_production_db
